version: "3"

services:
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
    networks:
      - frappe_docker_devcontainer_default

networks:
  frappe_docker_devcontainer_default:
    external: true
